In [ ]:
# pip install rpy2
# pip install GeoPy
# pip install gseapy
# pip install GEOparse
# pip install BioPython

In [ ]:
pip install GEOparse

In [3]:
import GEOparse
import numpy as np
import pandas as pd
import os

In [4]:
os.chdir("/home/kaderi/Feroj/5th/RA")

In [6]:
data = GEOparse.get_GEO(geo="GSE48780",destdir=None, annotate_gpl= True, how= "full")

14-Sep-2025 16:14:27 INFO GEOparse - No destination directory specified. Temporary files will be downloaded at /tmp/tmphhspmc93
14-Sep-2025 16:14:27 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE48nnn/GSE48780/soft/GSE48780_family.soft.gz to /tmp/tmphhspmc93/GSE48780_family.soft.gz
100%|██████████| 48.2M/48.2M [00:19<00:00, 2.60MB/s]
14-Sep-2025 16:14:49 DEBUG downloader - Size validation passed
14-Sep-2025 16:14:49 DEBUG downloader - Moving /tmp/tmpzgysk9mh to /tmp/tmphhspmc93/GSE48780_family.soft.gz
14-Sep-2025 16:14:49 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE48nnn/GSE48780/soft/GSE48780_family.soft.gz
14-Sep-2025 16:14:49 INFO GEOparse - Parsing /tmp/tmphhspmc93/GSE48780_family.soft.gz:
14-Sep-2025 16:14:49 DEBUG GEOparse - DATABASE: GeoMiame
14-Sep-2025 16:14:49 DEBUG GEOparse - SERIES: GSE48780
14-Sep-2025 16:14:49 DEBUG GEOparse - PLATFORM: GPL570
/home/kaderi/anaconda3/envs/Feroj_Ahmed/lib/python3.9/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Sep-2025 16:14:50 DEBUG GEOparse - SAMPLE: GSM1184435
14-Sep-2025 16:14:50 DEBUG GEOparse - SAMPLE: GSM1184436
14-Sep-2025 16:14:50 DEBUG GEOparse - SAMPLE: GSM1184437
14-Sep-2025 16:14:50 DEBUG GEOparse - SAMPLE: GSM1184438
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184439
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184440
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184441
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184442
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184443
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184444
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184445
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184446
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184447
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184448
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184449
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184450
14-Sep-2025 16:14:51 DEBUG GEOparse - SAMPLE: GSM1184451
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184452
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184453
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184454
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184455
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184456
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184457
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184458
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184459
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184460
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184461
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184462
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184463
14-Sep-2025 16:14:52 DEBUG GEOparse - SAMPLE: GSM1184464
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184465
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184466
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184467
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184468
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184469
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184470
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184471
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184472
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184473
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184474
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184475
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184476
14-Sep-2025 16:14:53 DEBUG GEOparse - SAMPLE: GSM1184477
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184478
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184479
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184480
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184481
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184482
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184483
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184484
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184485
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184486
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184487
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184488
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184489
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184490
14-Sep-2025 16:14:54 DEBUG GEOparse - SAMPLE: GSM1184491
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184492
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184493
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184494
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184495
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184496
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184497
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184498
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184499
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184500
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184501
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184502
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184503
14-Sep-2025 16:14:55 DEBUG GEOparse - SAMPLE: GSM1184504
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184505
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184506
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184507
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184508
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184509
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184510
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184511
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184512
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184513
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184514
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184515
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184516
14-Sep-2025 16:14:56 DEBUG GEOparse - SAMPLE: GSM1184517

In [8]:
Pheno_type_data = data.phenotype_data
Pheno_type_data.sample(10)

,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,taxid_ch1,...,contact_phone,contact_institute,contact_address,contact_city,contact_state,contact_zip/postal_code,contact_country,supplementary_file,series_id,data_row_count
GSM1184507,Rheumatoid Arthritis HF-306412,GSM1184507,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739
GSM1184447,Rheumatoid Arthritis HF-27955,GSM1184447,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739
GSM1184459,Rheumatoid Arthritis HF-21526,GSM1184459,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739
GSM1184440,Rheumatoid Arthritis HF-20639,GSM1184440,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739
GSM1184437,Rheumatoid Arthritis HF-21437,GSM1184437,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739
GSM1184486,Rheumatoid Arthritis HF-305132,GSM1184486,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739
GSM1184506,Rheumatoid Arthritis HF-306402,GSM1184506,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739
GSM1184438,Rheumatoid Arthritis HF-20660,GSM1184438,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739
GSM1184496,Rheumatoid Arthritis HF-306242,GSM1184496,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739
GSM1184491,Rheumatoid Arthritis HF-305492,GSM1184491,Public on Apr 22 2014,Jul 11 2013,Apr 22 2014,RNA,1,Rheumatoid Arthritis patient,Homo sapiens,9606,...,+1-650-467-8856,Genentech,1 DNA Way,South San Francisco,CA,94080,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1184...,GSE48780,42739

In [9]:
Pheno_type_data.columns

Index(['title', 'geo_accession', 'status', 'submission_date',
       'last_update_date', 'type', 'channel_count', 'source_name_ch1',
       'organism_ch1', 'taxid_ch1', 'characteristics_ch1.0.individual',
       'characteristics_ch1.1.tissue', 'characteristics_ch1.2.gender',
       'characteristics_ch1.3.joint location',
       'characteristics_ch1.4.inflammation', 'characteristics_ch1.5.batch',
       'treatment_protocol_ch1', 'molecule_ch1', 'extract_protocol_ch1',
       'label_ch1', 'label_protocol_ch1', 'hyb_protocol', 'scan_protocol',
       'description', 'data_processing', 'platform_id', 'contact_name',
       'contact_email', 'contact_phone', 'contact_institute',
       'contact_address', 'contact_city', 'contact_state',
       'contact_zip/postal_code', 'contact_country', 'supplementary_file',
       'series_id', 'data_row_count'],
      dtype='object')

In [14]:
Pheno_type_data["source_name_ch1"].value_counts()

source_name_ch1
Rheumatoid Arthritis patient    83
Name: count, dtype: int64

In [15]:
phe = Pheno_type_data[['geo_accession','source_name_ch1']]
phe.rename(columns={"source_name_ch1":"condition"},inplace=True)
print(phe.shape)
print(phe.head(3))

(83, 2)
           geo_accession                     condition
GSM1184435    GSM1184435  Rheumatoid Arthritis patient
GSM1184436    GSM1184436  Rheumatoid Arthritis patient
GSM1184437    GSM1184437  Rheumatoid Arthritis patient

/tmp/ipykernel_23016/2237559537.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phe.rename(columns={"source_name_ch1":"condition"},inplace=True)

In [16]:
feature_data = data.gpls[list(data.gpls.keys())[0]].table
feature_data.columns

Index(['ID', 'GB_ACC', 'SPOT_ID', 'Species Scientific Name', 'Annotation Date',
       'Sequence Type', 'Sequence Source', 'Target Description',
       'Representative Public ID', 'Gene Title', 'Gene Symbol',
       'ENTREZ_GENE_ID', 'RefSeq Transcript ID',
       'Gene Ontology Biological Process', 'Gene Ontology Cellular Component',
       'Gene Ontology Molecular Function'],
      dtype='object')

In [17]:
feature_data.sample(5)

,ID,GB_ACC,SPOT_ID,Species Scientific Name,Annotation Date,Sequence Type,Sequence Source,Target Description,Representative Public ID,Gene Title,Gene Symbol,ENTREZ_GENE_ID,RefSeq Transcript ID,Gene Ontology Biological Process,Gene Ontology Cellular Component,Gene Ontology Molecular Function
9629,1570101_at,BC039346,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:BC039346.1 /DB_XREF=gi:25058201 /TID=Hs2.40...,BC039346,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17917,208499_s_at,NM_006260,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,gb:NM_006260.1 /DB_XREF=gi:5453979 /GEN=PRKRI ...,NM_006260,"DnaJ (Hsp40) homolog, subfamily C, member 3",DNAJC3,5611,NM_006260,0006469 // negative regulation of protein kina...,0005737 // cytoplasm // traceable author state...,0004860 // protein kinase inhibitor activity /...
3395,1557034_s_at,AW193764,NaN,Homo sapiens,"Oct 6, 2014",Consensus sequence,GenBank,gb:AW193764 /DB_XREF=gi:6472463 /DB_XREF=xm30a...,AW193764,uncharacterized LOC100134445 /// WAS protein f...,LOC100134445 /// LOC100288778 /// LOC100653296...,374666 /// 375260 /// 375690 /// 653635 /// 10...,NM_182905 /// NM_198943 /// NM_199163 /// NR_0...,0006810 // transport // inferred from electron...,0005768 // endosome // inferred from electroni...,0003779 // actin binding // inferred from elec...
20540,211178_s_at,AF038602,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,gb:AF038602.1 /DB_XREF=gi:2921548 /FEA=FLmRNA ...,AF038602,proline-serine-threonine phosphatase interacti...,PSTPIP1,9051,NM_003978 /// XM_006720736 /// XM_006720737 //...,0002376 // immune system process // inferred f...,0001725 // stress fiber // inferred from elect...,0003779 // actin binding // inferred from elec...
11374,201926_s_at,BC001288,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,gb:BC001288.1 /DB_XREF=gi:12654888 /FEA=FLmRNA...,BC001288,"CD55 molecule, decay accelerating factor for c...",CD55,1604,NM_000574 /// NM_001114543 /// NM_001114544 //...,0002376 // immune system process // inferred f...,0005576 // extracellular region // traceable a...,0001618 // virus receptor activity // inferred...

In [28]:
fea = feature_data[['ID','Gene Symbol']]
fea.rename(columns={"Gene Symbol":'genes'},inplace= True)
print(fea.shape)
print(fea.head(5))

(54675, 2)
          ID             genes
0  1007_s_at  DDR1 /// MIR4640
1    1053_at              RFC2
2     117_at             HSPA6
3     121_at              PAX8
4  1255_g_at            GUCA1A

/tmp/ipykernel_23016/1621163233.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fea.rename(columns={"Gene Symbol":'genes'},inplace= True)

In [29]:
series_mat = data.pivot_samples(values="VALUE")
print(series_mat.shape)
series_mat.head(5)

(42739, 83)

name,GSM1184435,GSM1184436,GSM1184437,GSM1184438,GSM1184439,GSM1184440,GSM1184441,GSM1184442,GSM1184443,GSM1184444,...,GSM1184508,GSM1184509,GSM1184510,GSM1184511,GSM1184512,GSM1184513,GSM1184514,GSM1184515,GSM1184516,GSM1184517
ID_REF,,,,,,,,,,,,,,,,,,,,,
1007_s_at,9.743821,10.011614,9.805600,9.812442,9.865165,9.584766,9.846066,9.630419,10.068919,9.784129,...,9.975600,9.629524,9.322266,9.790046,9.866067,9.820116,9.609037,9.915160,10.017417,9.473125
1053_at,8.093348,8.231049,8.081838,8.224621,7.997792,7.790269,7.913206,8.416506,8.408523,8.414991,...,8.388854,8.828610,8.673263,8.305593,8.734991,8.309171,8.657461,8.765844,8.492934,8.487457
117_at,9.973304,9.803313,7.969290,10.124580,9.493979,9.178818,9.382873,9.490957,9.697521,8.756782,...,10.698044,10.226216,9.294229,9.288750,9.684232,9.728821,8.795072,10.038430,9.586756,10.480295
121_at,10.327259,10.568496,10.036745,10.398224,10.450661,10.142537,10.570322,10.380721,10.328502,10.505511,...,10.093975,10.436215,10.106989,10.514553,10.515980,10.267348,10.343344,10.428593,10.728603,10.387710
1255_g_at,5.821090,6.070927,6.024875,5.691534,5.606675,5.475440,5.566837,5.603404,6.641495,6.258071,...,6.028965,6.211843,5.833729,6.810665,7.669359,6.500500,6.465627,7.376486,5.924246,6.182502

In [30]:
new_series_mat = series_mat.reset_index()
new_series_mat

name,ID_REF,GSM1184435,GSM1184436,GSM1184437,GSM1184438,GSM1184439,GSM1184440,GSM1184441,GSM1184442,GSM1184443,...,GSM1184508,GSM1184509,GSM1184510,GSM1184511,GSM1184512,GSM1184513,GSM1184514,GSM1184515,GSM1184516,GSM1184517
0,1007_s_at,9.743821,10.011614,9.805600,9.812442,9.865165,9.584766,9.846066,9.630419,10.068919,...,9.975600,9.629524,9.322266,9.790046,9.866067,9.820116,9.609037,9.915160,10.017417,9.473125
1,1053_at,8.093348,8.231049,8.081838,8.224621,7.997792,7.790269,7.913206,8.416506,8.408523,...,8.388854,8.828610,8.673263,8.305593,8.734991,8.309171,8.657461,8.765844,8.492934,8.487457
2,117_at,9.973304,9.803313,7.969290,10.124580,9.493979,9.178818,9.382873,9.490957,9.697521,...,10.698044,10.226216,9.294229,9.288750,9.684232,9.728821,8.795072,10.038430,9.586756,10.480295
3,121_at,10.327259,10.568496,10.036745,10.398224,10.450661,10.142537,10.570322,10.380721,10.328502,...,10.093975,10.436215,10.106989,10.514553,10.515980,10.267348,10.343344,10.428593,10.728603,10.387710
4,1255_g_at,5.821090,6.070927,6.024875,5.691534,5.606675,5.475440,5.566837,5.603404,6.641495,...,6.028965,6.211843,5.833729,6.810665,7.669359,6.500500,6.465627,7.376486,5.924246,6.182502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42734,91703_at,9.357186,9.626270,8.999233,9.955437,9.237961,9.295171,9.259673,9.532704,9.909298,...,10.078372,9.944883,9.387425,9.659001,10.082450,9.554201,9.584769,10.079241,9.862046,10.024919
42735,91816_f_at,8.780144,10.017439,8.860881,9.363462,8.215079,8.674453,9.166656,10.003440,8.770869,...,10.109245,9.538629,9.482037,9.574222,9.036073,9.070161,10.248737,8.626594,9.143364,9.423518
42736,91826_at,8.158232,7.848388,8.234873,8.227601,7.769249,7.822994,8.073554,7.848292,7.882198,...,7.788305,7.695372,7.413453,7.615610,7.602265,7.880218,7.691121,7.603541,7.924526,7.799227
42737,91920_at,9.322756,9.163797,9.097154,9.203284,9.383143,9.190333,9.203016,9.379914,9.156574,...,8.927099,9.033473,8.967397,9.157844,9.151644,9.517148,9.097343,9.095926,9.381465,9.211691
42738,91952_at,9.033069,9.512152,9.134806,9.686379,8.973599,8.935740,9.213207,9.020041,9.226373,...,9.545442,9.692034,9.430726,9.137372,9.379530,9.501182,9.296298,9.399567,9.344915,9.490295

In [31]:
print(fea.info())
print(new_series_mat.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54675 entries, 0 to 54674
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      54675 non-null  object
 1   genes   45782 non-null  object
dtypes: object(2)
memory usage: 854.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42739 entries, 0 to 42738
Data columns (total 84 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID_REF      42739 non-null  object
 1   GSM1184435  42739 non-null  float64
 2   GSM1184436  42739 non-null  float64
 3   GSM1184437  42739 non-null  float64
 4   GSM1184438  42739 non-null  float64
 5   GSM1184439  42739 non-null  float64
 6   GSM1184440  42739 non-null  float64
 7   GSM1184441  42739 non-null  float64
 8   GSM1184442  42739 non-null  float64
 9   GSM1184443  42739 non-null  float64
 10  GSM1184444  42739 non-null  float64
 11  GSM1184445  42739 non-null  float64
 12  GSM1184446  42739 non-null  float64
 13  GSM1184447  42739 non-null  float64
 14  GSM1184448  42739 non-null  float64
 15  GSM1184449  42739 non-null  float64
 16  GSM1184450  42739 non-null  float64
 17  GSM1184451  42739 non-null  float64
 18  GSM1184452  42739 non-null  float64
 19  GSM1184453  42739 non-null  float64
 20  GSM1184454  42739 non-null  float64
 21  GSM1184455  42739 non-null  float64
 22  GSM1184456  42739 non-null  float64
 23  GSM1184457  42739 non-null  float64
 24  GSM1184458  42739 non-null  float64
 25  GSM1184459  42739 non-null  float64
 26  GSM1184460  42739 non-null  float64
 27  GSM1184461  42739 non-null  float64
 28  GSM1184462  42739 non-null  float64
 29  GSM1184463  42739 non-null  float64
 30  GSM1184464  42739 non-null  float64
 31  GSM1184465  42739 non-null  float64
 32  GSM1184466  42739 non-null  float64
 33  GSM1184467  42739 non-null  float64
 34  GSM1184468  42739 non-null  float64
 35  GSM1184469  42739 non-null  float64
 36  GSM1184470  42739 non-null  float64
 37  GSM1184471  42739 non-null  float64
 38  GSM1184472  42739 non-null  float64
 39  GSM1184473  42739 non-null  float64
 40  GSM1184474  42739 non-null  float64
 41  GSM1184475  42739 non-null  float64
 42  GSM1184476  42739 non-null  float64
 43  GSM1184477  42739 non-null  float64
 44  GSM1184478  42739 non-null  float64
 45  GSM1184479  42739 non-null  float64
 46  GSM1184480  42739 non-null  float64
 47  GSM1184481  42739 non-null  float64
 48  GSM1184482  42739 non-null  float64
 49  GSM1184483  42739 non-null  float64
 50  GSM1184484  42739 non-null  float64
 51  GSM1184485  42739 non-null  float64
 52  GSM1184486  42739 non-null  float64
 53  GSM1184487  42739 non-null  float64
 54  GSM1184488  42739 non-null  float64
 55  GSM1184489  42739 non-null  float64
 56  GSM1184490  42739 non-null  float64
 57  GSM1184491  42739 non-null  float64
 58  GSM1184492  42739 non-null  float64
 59  GSM1184493  42739 non-null  float64
 60  GSM1184494  42739 non-null  float64
 61  GSM1184495  42739 non-null  float64
 62  GSM1184496  42739 non-null  float64
 63  GSM1184497  42739 non-null  float64
 64  GSM1184498  42739 non-null  float64
 65  GSM1184499  42739 non-null  float64
 66  GSM1184500  42739 non-null  float64
 67  GSM1184501  42739 non-null  float64
 68  GSM1184502  42739 non-null  float64
 69  GSM1184503  42739 non-null  float64
 70  GSM1184504  42739 non-null  float64
 71  GSM1184505  42739 non-null  float64
 72  GSM1184506  42739 non-null  float64
 73  GSM1184507  42739 non-null  float64
 74  GSM1184508  42739 non-null  float64
 75  GSM1184509  42739 non-null  float64
 76  GSM1184510  42739 non-null  float64
 77  GSM1184511  42739 non-null  float64
 78  GSM1184512  42739 non-null  float64
 79  GSM1184513  42739 non-null  float64
 80  GSM1184514  42739 non-null  float64
 81  GSM1184515  42739 non-null  float64
 82  GSM1184516  42739 non-null  float64
 83  GSM1184517  42739 non-null  float64
dtypes: float64(83), object(1)
memory usage: 27.4+ MB
None

In [32]:
series_mat_official = new_series_mat.merge(right=fea, how='inner', left_on='ID_REF', right_on="ID",sort=True)
series_mat_official.head(15)

,ID_REF,GSM1184435,GSM1184436,GSM1184437,GSM1184438,GSM1184439,GSM1184440,GSM1184441,GSM1184442,GSM1184443,...,GSM1184510,GSM1184511,GSM1184512,GSM1184513,GSM1184514,GSM1184515,GSM1184516,GSM1184517,ID,genes
0,1007_s_at,9.743821,10.011614,9.805600,9.812442,9.865165,9.584766,9.846066,9.630419,10.068919,...,9.322266,9.790046,9.866067,9.820116,9.609037,9.915160,10.017417,9.473125,1007_s_at,DDR1 /// MIR4640
1,1053_at,8.093348,8.231049,8.081838,8.224621,7.997792,7.790269,7.913206,8.416506,8.408523,...,8.673263,8.305593,8.734991,8.309171,8.657461,8.765844,8.492934,8.487457,1053_at,RFC2
2,117_at,9.973304,9.803313,7.969290,10.124580,9.493979,9.178818,9.382873,9.490957,9.697521,...,9.294229,9.288750,9.684232,9.728821,8.795072,10.038430,9.586756,10.480295,117_at,HSPA6
3,121_at,10.327259,10.568496,10.036745,10.398224,10.450661,10.142537,10.570322,10.380721,10.328502,...,10.106989,10.514553,10.515980,10.267348,10.343344,10.428593,10.728603,10.387710,121_at,PAX8
4,1255_g_at,5.821090,6.070927,6.024875,5.691534,5.606675,5.475440,5.566837,5.603404,6.641495,...,5.833729,6.810665,7.669359,6.500500,6.465627,7.376486,5.924246,6.182502,1255_g_at,GUCA1A
5,1294_at,9.534758,9.565518,9.157475,9.604803,9.267098,9.635226,9.138716,9.129931,9.318149,...,8.819251,9.223405,9.337459,9.353947,9.109418,9.411465,9.652624,9.643736,1294_at,MIR5193 /// UBA7
6,1316_at,6.932658,7.024655,7.262371,7.180283,6.823256,6.831282,7.019917,6.908889,6.926083,...,8.194336,8.454495,7.774389,7.970838,7.808801,7.623544,7.626071,7.827306,1316_at,THRA
7,1320_at,7.361224,7.612177,7.617533,7.626073,7.569805,7.481108,7.541999,7.470446,7.698628,...,7.278484,7.655225,7.997375,7.241838,7.911294,7.720739,7.607692,7.384271,1320_at,PTPN21
8,1405_i_at,10.165676,9.497645,8.199030,10.740506,8.301230,8.509237,8.706703,9.206794,7.939896,...,7.038879,7.140493,7.290232,9.689539,7.105348,8.162329,9.923001,10.274807,1405_i_at,CCL5
9,1431_at,6.074374,6.188541,6.072452,6.069668,6.054834,6.257922,6.014977,5.997510,6.146447,...,6.560363,6.381254,6.590076,6.477561,6.610449,6.537636,6.405390,6.501530,1431_at,CYP2E1
10,1438_at,8.824886,9.156468,9.367921,8.613045,8.812507,8.566378,8.474600,8.727106,8.438137,...,8.126441,9.184463,8.496518,9.469559,9.945097,8.314602,8.806459,8.467892,1438_at,EPHB3
11,1487_at,9.263881,9.110664,9.040681,9.503883,9.186489,9.101588,9.268580,9.417363,9.143484,...,9.780010,9.226981,9.416574,9.182977,9.303839,9.446831,9.154948,9.299324,1487_at,ESRRA
12,1494_f_at,8.045702,7.877913,8.256890,8.039890,8.053968,7.528786,8.309935,7.861901,8.136697,...,7.910616,8.025817,7.846389,8.112211,7.896720,7.882970,8.209253,7.908474,1494_f_at,CYP2A6
13,1552256_a_at,10.567851,10.049177,9.447583,10.353340,10.034364,10.324427,10.266155,9.987573,10.798226,...,10.435215,10.703115,10.952546,9.856208,9.719626,10.983581,10.470554,10.664653,1552256_a_at,SCARB1
14,1552257_a_at,9.058685,9.470070,9.283285,9.370844,8.983069,8.862322,9.046686,9.087969,9.032125,...,9.432960,9.589953,9.143691,9.346598,9.057524,8.958618,8.996202,9.145934,1552257_a_at,TTLL12

#### if left_on and right_on columns dtypes are different then it will not merge. to solve this reason make the dtype of both coluns same by using the syntax below
new_series_mat.astype({"GSM3108231":'object'}, inpalce = True)

#### Change the "object" yo your desitre data type

In [33]:
series_mat_official.drop(['ID',"ID_REF"],axis=1, inplace= True)
series_mat_official

,GSM1184435,GSM1184436,GSM1184437,GSM1184438,GSM1184439,GSM1184440,GSM1184441,GSM1184442,GSM1184443,GSM1184444,...,GSM1184509,GSM1184510,GSM1184511,GSM1184512,GSM1184513,GSM1184514,GSM1184515,GSM1184516,GSM1184517,genes
0,9.743821,10.011614,9.805600,9.812442,9.865165,9.584766,9.846066,9.630419,10.068919,9.784129,...,9.629524,9.322266,9.790046,9.866067,9.820116,9.609037,9.915160,10.017417,9.473125,DDR1 /// MIR4640
1,8.093348,8.231049,8.081838,8.224621,7.997792,7.790269,7.913206,8.416506,8.408523,8.414991,...,8.828610,8.673263,8.305593,8.734991,8.309171,8.657461,8.765844,8.492934,8.487457,RFC2
2,9.973304,9.803313,7.969290,10.124580,9.493979,9.178818,9.382873,9.490957,9.697521,8.756782,...,10.226216,9.294229,9.288750,9.684232,9.728821,8.795072,10.038430,9.586756,10.480295,HSPA6
3,10.327259,10.568496,10.036745,10.398224,10.450661,10.142537,10.570322,10.380721,10.328502,10.505511,...,10.436215,10.106989,10.514553,10.515980,10.267348,10.343344,10.428593,10.728603,10.387710,PAX8
4,5.821090,6.070927,6.024875,5.691534,5.606675,5.475440,5.566837,5.603404,6.641495,6.258071,...,6.211843,5.833729,6.810665,7.669359,6.500500,6.465627,7.376486,5.924246,6.182502,GUCA1A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42734,9.357186,9.626270,8.999233,9.955437,9.237961,9.295171,9.259673,9.532704,9.909298,9.675533,...,9.944883,9.387425,9.659001,10.082450,9.554201,9.584769,10.079241,9.862046,10.024919,EHBP1L1
42735,8.780144,10.017439,8.860881,9.363462,8.215079,8.674453,9.166656,10.003440,8.770869,9.804088,...,9.538629,9.482037,9.574222,9.036073,9.070161,10.248737,8.626594,9.143364,9.423518,MEX3D
42736,8.158232,7.848388,8.234873,8.227601,7.769249,7.822994,8.073554,7.848292,7.882198,8.030952,...,7.695372,7.413453,7.615610,7.602265,7.880218,7.691121,7.603541,7.924526,7.799227,EPS8L1
42737,9.322756,9.163797,9.097154,9.203284,9.383143,9.190333,9.203016,9.379914,9.156574,9.195387,...,9.033473,8.967397,9.157844,9.151644,9.517148,9.097343,9.095926,9.381465,9.211691,BCAN
42738,9.033069,9.512152,9.134806,9.686379,8.973599,8.935740,9.213207,9.020041,9.226373,9.645688,...,9.692034,9.430726,9.137372,9.379530,9.501182,9.296298,9.399567,9.344915,9.490295,DCAF15

In [34]:
series_mat_official.sort_index(axis= 1, ascending= False, inplace= True)
series_mat_official

,genes,GSM1184517,GSM1184516,GSM1184515,GSM1184514,GSM1184513,GSM1184512,GSM1184511,GSM1184510,GSM1184509,...,GSM1184444,GSM1184443,GSM1184442,GSM1184441,GSM1184440,GSM1184439,GSM1184438,GSM1184437,GSM1184436,GSM1184435
0,DDR1 /// MIR4640,9.473125,10.017417,9.915160,9.609037,9.820116,9.866067,9.790046,9.322266,9.629524,...,9.784129,10.068919,9.630419,9.846066,9.584766,9.865165,9.812442,9.805600,10.011614,9.743821
1,RFC2,8.487457,8.492934,8.765844,8.657461,8.309171,8.734991,8.305593,8.673263,8.828610,...,8.414991,8.408523,8.416506,7.913206,7.790269,7.997792,8.224621,8.081838,8.231049,8.093348
2,HSPA6,10.480295,9.586756,10.038430,8.795072,9.728821,9.684232,9.288750,9.294229,10.226216,...,8.756782,9.697521,9.490957,9.382873,9.178818,9.493979,10.124580,7.969290,9.803313,9.973304
3,PAX8,10.387710,10.728603,10.428593,10.343344,10.267348,10.515980,10.514553,10.106989,10.436215,...,10.505511,10.328502,10.380721,10.570322,10.142537,10.450661,10.398224,10.036745,10.568496,10.327259
4,GUCA1A,6.182502,5.924246,7.376486,6.465627,6.500500,7.669359,6.810665,5.833729,6.211843,...,6.258071,6.641495,5.603404,5.566837,5.475440,5.606675,5.691534,6.024875,6.070927,5.821090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42734,EHBP1L1,10.024919,9.862046,10.079241,9.584769,9.554201,10.082450,9.659001,9.387425,9.944883,...,9.675533,9.909298,9.532704,9.259673,9.295171,9.237961,9.955437,8.999233,9.626270,9.357186
42735,MEX3D,9.423518,9.143364,8.626594,10.248737,9.070161,9.036073,9.574222,9.482037,9.538629,...,9.804088,8.770869,10.003440,9.166656,8.674453,8.215079,9.363462,8.860881,10.017439,8.780144
42736,EPS8L1,7.799227,7.924526,7.603541,7.691121,7.880218,7.602265,7.615610,7.413453,7.695372,...,8.030952,7.882198,7.848292,8.073554,7.822994,7.769249,8.227601,8.234873,7.848388,8.158232
42737,BCAN,9.211691,9.381465,9.095926,9.097343,9.517148,9.151644,9.157844,8.967397,9.033473,...,9.195387,9.156574,9.379914,9.203016,9.190333,9.383143,9.203284,9.097154,9.163797,9.322756
42738,DCAF15,9.490295,9.344915,9.399567,9.296298,9.501182,9.379530,9.137372,9.430726,9.692034,...,9.645688,9.226373,9.020041,9.213207,8.935740,8.973599,9.686379,9.134806,9.512152,9.033069

In [ ]:
# phe['condition'].unique()

array(['Rheumatoid Arthritis patient'], dtype=object)

In [ ]:
# for i,j in enumerate(phe['geo_accession'].values):
#     series_mat_official.rename(columns={j : phe['condition'].to_list()[i]}, inplace= True)

# series_mat_official

#### from here we can start to preprocese the data for <span style = "color: red"> pycombat </span>

In [ ]:
# series_mat_official = pd.read_csv(filepath_or_buffer='GSE48780_unclean.csv')
# print(series_mat_official.shape)

In [27]:
series_mat_official = series_mat_official[~series_mat_official['gene'].isna()]
series_mat_official.head(5)

,gene,GSM1184517,GSM1184516,GSM1184515,GSM1184514,GSM1184513,GSM1184512,GSM1184511,GSM1184510,GSM1184509,...,GSM1184444,GSM1184443,GSM1184442,GSM1184441,GSM1184440,GSM1184439,GSM1184438,GSM1184437,GSM1184436,GSM1184435
0,DDR1 /// MIR4640,9.473125,10.017417,9.915160,9.609037,9.820116,9.866067,9.790046,9.322266,9.629524,...,9.784129,10.068919,9.630419,9.846066,9.584766,9.865165,9.812442,9.805600,10.011614,9.743821
1,RFC2,8.487457,8.492934,8.765844,8.657461,8.309171,8.734991,8.305593,8.673263,8.828610,...,8.414991,8.408523,8.416506,7.913206,7.790269,7.997792,8.224621,8.081838,8.231049,8.093348
2,HSPA6,10.480295,9.586756,10.038430,8.795072,9.728821,9.684232,9.288750,9.294229,10.226216,...,8.756782,9.697521,9.490957,9.382873,9.178818,9.493979,10.124580,7.969290,9.803313,9.973304
3,PAX8,10.387710,10.728603,10.428593,10.343344,10.267348,10.515980,10.514553,10.106989,10.436215,...,10.505511,10.328502,10.380721,10.570322,10.142537,10.450661,10.398224,10.036745,10.568496,10.327259
4,GUCA1A,6.182502,5.924246,7.376486,6.465627,6.500500,7.669359,6.810665,5.833729,6.211843,...,6.258071,6.641495,5.603404,5.566837,5.475440,5.606675,5.691534,6.024875,6.070927,5.821090

In [ ]:
series_mat_official["genes"].values
length_gene = []
for i in series_mat_official["genes"].values:
    length_gene.append(len(i))




longest_character = series_mat_official["genes"].values[np.argmax(length_gene)] 
longest_character

#### if the indetifier the longest gene in the sample is giving error(like 'float' has no len())the attempt the code below

In [ ]:
series_mat_official["gene"].values
length_gene = []
for i in series_mat_official["gene"].values:
    if isinstance(i, float):
        length_gene.append(0)
    else:
        length_gene.append(len(i))



longest_character = series_mat_official["gene"].values[np.argmax(length_gene)] 
longest_character

##### Now we  can decide what type of dtring analysis is needed

In [ ]:
#### run this if the longest gene character has ///


genes = series_mat_official['genes'].str.split("///")

official_gene_symbol = []

for i in genes:
    if isinstance(i, float):
        official_gene_symbol.append(i)
    else:
        official_gene_symbol.append(i[0])

In [ ]:
#### run this if the longest gene character has //


genes = series_mat_official['genes'].str.split("//")

official_gene_symbol = []

for i in genes:
    if isinstance(i, float):
        official_gene_symbol.append(i)
    elif '---' in i[0]:
        official_gene_symbol.append(pd.NA)
    elif len(i)  > 1:
        official_gene_symbol.append(i[1])
    else:
        official_gene_symbol.append(i[0])

In [ ]:
print(len(official_gene_symbol ))
series_mat_official['genes']=official_gene_symbol 
series_mat_official['genes'] =  series_mat_official["genes"].str.strip()

In [ ]:
series_mat_official.dropna(subset="genes", inplace=True)
series_mat_official.shape

In [ ]:
duplicate_genes = series_mat_official["genes"][series_mat_official.duplicated(subset=("genes"))].unique()
print(duplicate_genes[0:11])
print(len(duplicate_genes))

In [ ]:
unique_data = series_mat_official.drop_duplicates(subset='genes', keep= False)
unique_data.shape

In [ ]:
data3 = pd.DataFrame(index= duplicate_genes, columns= series_mat_official.columns)

for i in duplicate_genes:
    gene = series_mat_official[series_mat_official['genes']==i].set_index("genes")
    value = gene.mean(axis=0).to_list()
    value.insert(0, i)
    data3.loc[i,:] = value

In [ ]:
data4  = pd.concat((unique_data,data3),axis = 0,ignore_index=True)
data4.shape

In [ ]:
data4.to_csv("GSE48780_clean.csv",index=False)

In [ ]:
data4.sample(10)

In [ ]:
data4.rename(columns={

                     'colorectal carcinoma tissues':"Disease",
                     'non-cancerous colorectal tissue':"Control",
                     },inplace= True)

In [ ]:
data4[['genes',"Control","Disease"]]

In [ ]:
data4.sort_index(axis=)

In [ ]:
data4[['genes',"Control","Disease"]].to_csv("/home/kaderi/Feroj/zoology/GSE24287/GSE24287_clean.csv",index= False)