### Here we will find out all the important epitope with different filtering

In [1]:
import pandas as pd
import numpy as np
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio import AlignIO
import os
import pathlib

In [2]:
os.chdir("/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5")

In [49]:
alignment_vp1 = AlignIO.read("vp4_aligned.fasta", "fasta")
print(alignment_vp1)

Alignment with 5 rows and 66 columns
GAQVSKQNVGSHENSVSASGGSVIKYFNINYYKDSASSGLTKQD...ALM HRV-C2_VP4
GAQVSRQSVGSHETMIHAGTGAVVKYFNVNYYKDAASSGLTKQD...ALM HRV-C6_VP4
GAQVSRQKVGSHDNAINASSGSVVKYFNINYYKDAASSGLSKQD...ALM HRV-C9_VP4
GAQVSRQNNGTHESGVTANNGSVIKYFNINYYKDSASSGLSRQD...ALM HRV-C15_VP4
GAQVSKQSVGAHETTVHAGSGAVVKYFNINYYKDAASSGLTKQD...ALM HRV-C43_VP4

In [ ]:

consensus_sequence = ""
for residue in range(0,alignment_vp1.get_alignment_length()):
    unique_chars = ""
    for i in alignment_vp1[:,residue]:
        if i in unique_chars:
            pass
        else:
            unique_chars+=i
    char_dict = dict()
    for j in unique_chars:

        char_dict.update({f"{j}":alignment_vp1[:,residue].count(j)})

    char_dict
    dict_value= list(char_dict.values())
    for keys, values in char_dict.items():
        
        if keys != "-":
        
            if values == max(dict_value):

                consensus_sequence+= keys
                break  ### if there is more than two residue occurs most then it will take the first one alphabetically#####
        else:
            dict_value.remove(max(dict_value))
            
            if values == max(dict_value):
                consensus_sequence+= keys
                break


consensus_sequence

'GPEHEFGMALIKRNCHIATTDRGEFNLLGIHDNCAVIPTHAECEDTILIDGVETKILKQQIITDENDVDTEITLLWLDRNEKFRDIRRFIPEYQREWHNMRLVTNVSKFPMLDVEVGTVIPYGEINLSGNPTCRLLKYDYPTKPGQCGGVIGNTGNIVGIHVGGNG'

In [31]:
len(consensus_sequence)

166

In [ ]:
# full_conserve_sequence =""
# for i in consensus_sequence:
#     if i != "-":
#         full_conserve_sequence += i
#     else:
#         pass
# full_conserve_sequence

In [50]:
conserved = ""
for i in range(alignment_vp1.get_alignment_length()):
    column = alignment_vp1[:, i]
    if column.count(column[0]) == len(column) and column[0] != "-":
        conserved += column[0]
    else:
        conserved += "-"

print("Conserved pattern:\n", conserved)

Conserved pattern:
 GAQVS-Q--G-H-----A--G-V-KYFN-NYYKD-ASSGL--QDFSQDPSKFTQP----L-NPALM

In [51]:
conserve_epitops= []
for i in conserved.split("-"):
    
    if len(i)>=5:
        print(f'position {conserved.index(i)+1} ', i)
        conserve_epitops.append(i)
    else:
        pass
conserve_epitops

position 1  GAQVS
position 30  NYYKD
position 36  ASSGL
position 43  QDFSQDPSKFTQP
position 62  NPALM

['GAQVS', 'NYYKD', 'ASSGL', 'QDFSQDPSKFTQP', 'NPALM']

In [148]:
len(conserved)

125

In [120]:
## Here we will call the b cell/t-cell eptopes datafram

bpred_result = pd.read_csv(filepath_or_buffer="/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5/result_collection/t1_2A_iedb.csv")
bpred_result

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,ILLALTADL,10,18,9,HLA-A*02:01,10,0.55,ILLALTADL,ILLALTADL,0.302525,0.55
1,1,ITAGGDNHV,102,110,9,HLA-A*02:01,102,2.90,ITAGGDNHV,ITAGGDNHV,0.029095,2.90
2,1,ILIGEGPCS,76,84,9,HLA-A*02:01,76,4.60,ILIGEGPCS,ILIGEGPCS,0.011978,4.60
3,1,SYYPKHIQY,66,74,9,HLA-A*02:01,66,4.60,SYYPKHIQY,SYYPKHIQY,0.011817,4.60
4,1,LALTADLQV,12,20,9,HLA-A*02:01,12,4.70,LALTADLQV,LALTADLQV,0.011289,4.70
...,...,...,...,...,...,...,...,...,...,...,...,...
110,1,IGMITAGGD,99,107,9,HLA-A*02:01,99,95.00,IGMITAGGD,IGMITAGGD,0.000001,95.00
111,1,GCYYCKSRD,39,47,9,HLA-A*02:01,39,100.00,GCYYCKSRD,GCYYCKSRD,0.000000,100.00
112,1,PCSPGDCGG,82,90,9,HLA-A*02:01,82,100.00,PCSPGDCGG,PCSPGDCGG,0.000000,100.00
113,1,PDCDCTSGC,32,40,9,HLA-A*02:01,32,100.00,PDCDCTSGC,PDCDCTSGC,0.000000,100.00
114,1,PDTIPDCDC,28,36,9,HLA-A*02:01,28,100.00,PDTIPDCDC,PDTIPDCDC,0.000000,100.00

In [123]:
#for t-cell 1
t_cell_result_1 = bpred_result[bpred_result["netmhcpan_el percentile"] <10]
t_cell_result_1

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,ILLALTADL,10,18,9,HLA-A*02:01,10,0.55,ILLALTADL,ILLALTADL,0.302525,0.55
1,1,ITAGGDNHV,102,110,9,HLA-A*02:01,102,2.90,ITAGGDNHV,ITAGGDNHV,0.029095,2.90
2,1,ILIGEGPCS,76,84,9,HLA-A*02:01,76,4.60,ILIGEGPCS,ILIGEGPCS,0.011978,4.60
3,1,SYYPKHIQY,66,74,9,HLA-A*02:01,66,4.60,SYYPKHIQY,SYYPKHIQY,0.011817,4.60
4,1,LALTADLQV,12,20,9,HLA-A*02:01,12,4.70,LALTADLQV,LALTADLQV,0.011289,4.70
5,1,CVAHDWYEI,54,62,9,HLA-A*02:01,54,5.20,CVAHDWYEI,CVAHDWYEI,0.009216,5.20
6,1,KLLCVHGVI,91,99,9,HLA-A*02:01,91,5.60,KLLCVHGVI,KLLCVHGVI,0.007818,5.60
7,1,NTILLALTA,8,16,9,HLA-A*02:01,8,6.10,NTILLALTA,NTILLALTA,0.006692,6.10
8,1,LTTPNDNTI,2,10,9,HLA-A*02:01,2,6.90,LTTPNDNTI,LTTPNDNTI,0.004973,6.90
9,1,TPNDNTILL,4,12,9,HLA-A*02:01,4,7.00,TPNDNTILL,TPNDNTILL,0.004950,7.00
10,1,IQYNILIGE,72,80,9,HLA-A*02:01,72,9.60,IQYNILIGE,IQYNILIGE,0.002339,9.60
11,1,DLQVDGANV,17,25,9,HLA-A*02:01,17,9.60,DLQVDGANV,DLQVDGANV,0.002327,9.60
12,1,KSRDRYYPV,44,52,9,HLA-A*02:01,44,9.80,KSRDRYYPV,KSRDRYYPV,0.002222,9.80

In [7]:
# for bepripred
epitope_pred = ""

for i,j in enumerate(bpred_result["EpitopeProbability"]):
    if j < 0.5:
        epitope_pred+="-"
    else:
        epitope_pred+=bpred_result['AminoAcid'][i]
epitope_pred

'----SLNTIVA-GEWPSYLSDLDATSVDKPTHPETSSD-FYTLESVTWQGSSRGWWW--PDC-----VFGQNMYHHSMGRSGYIIHTQCNATKFHSGCL----VPEHQLAYIGGGGVNVKYEHTHPGEG-------GASNDRSNNNPDED-FFNCNGT-------FPHQMINLRTNNSSTIVV--------DNMLRHNNVSLV--------'

In [ ]:
## now we will cut the epitope separate then
epitope_to_check= []
for i in epitope_pred.split("-"):
    if len(i)>=7:
        epitope_to_check.append(i)
    else:
        pass
epitope_to_check

NameError: name 'epitope_pred' is not defined

In [126]:
##for t-cell
## now we will cut the epitope separate then

epitope_to_check = t_cell_result_1['peptide'].values
epitope_to_check

array(['ILLALTADL', 'ITAGGDNHV', 'ILIGEGPCS', 'SYYPKHIQY', 'LALTADLQV',
       'CVAHDWYEI', 'KLLCVHGVI', 'NTILLALTA', 'LTTPNDNTI', 'TPNDNTILL',
       'IQYNILIGE', 'DLQVDGANV', 'KSRDRYYPV'], dtype=object)

In [ ]:
conserve_epitops= []
for i in conserved.split("-"):
    if len(i)>=5:
        conserve_epitops.append(i)
    else:
        pass
conserve_epitops

68
86

['YYPKHIQY', 'PGDCGGKLLC']

In [17]:
conserved[68:76]

'YYPKHIQY'

In [127]:

result_table = pd.DataFrame(columns=("conserve_regions",
                                     'candidate_epitope',
                                     'conservence_presence'))
for a in conserve_epitops:
    l = ''
    k = ''
    for i in range(0,len(a)):

        b = a[i:]
        if b in l:
            break
        elif len(b)>=4:
            for epitopes in epitope_to_check:
                if b in epitopes:
                    print(f"{b} present in {epitopes}")
                    l += b
                    result_table_1 = pd.DataFrame({
                                        "conserve_regions":[a],
                                        "candidate_epitope":[epitopes],
                                        "conservence_presence":[l]})
                    result_table = pd.concat((result_table,result_table_1),axis = 0)
                    break

YYPKHIQY present in SYYPKHIQY
KLLC present in KLLCVHGVI

In [128]:
result_table.describe()

       conserve_regions candidate_epitope conservence_presence
count                 2                 2                    2
unique                2                 2                    2
top            YYPKHIQY         SYYPKHIQY             YYPKHIQY
freq                  1                 1                    1

In [129]:
result_table["candidate_epitope"].unique()

array(['SYYPKHIQY', 'KLLCVHGVI'], dtype=object)

In [131]:
conserve_regions_table = []
candidate_epitope_table = []
conserve_epitope_presence = []
for i in result_table["candidate_epitope"].unique():
    index_conserve = result_table[result_table["candidate_epitope"]== i ]['conserve_regions'].values
    presence_conserve = result_table[result_table["candidate_epitope"]== i ]['conservence_presence'].values
    conserve_epitope_region_table = ''
    conserve_epitope_presence_table = ''
    if len(index_conserve)> 1:
        for j in index_conserve:
            conserve_epitope_region_table += f"{j}"
            conserve_epitope_region_table += ","
        for k in presence_conserve:
            conserve_epitope_presence_table += f"{k}"
            conserve_epitope_presence_table += ","
    else:
        conserve_epitope_region_table += f"{index_conserve[0]}"
        conserve_epitope_presence_table += f"{presence_conserve[0]}"
    conserve_regions_table.append(i)
    candidate_epitope_table.append(conserve_epitope_region_table)
    conserve_epitope_presence.append(conserve_epitope_presence_table)

In [132]:
final_table = pd.DataFrame({"conserve_region":candidate_epitope_table,
                            "epitope":conserve_regions_table,
                            "conservence_presence":conserve_epitope_presence,
                            })
final_table

  conserve_region    epitope conservence_presence
0        YYPKHIQY  SYYPKHIQY             YYPKHIQY
1      PGDCGGKLLC  KLLCVHGVI                 KLLC

In [144]:
final_table.to_csv(path_or_buf="/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5/result_collection/2A_CTL/2A_CTL_final_candidate_epitope.csv")

In [140]:
t_cell_result_1[t_cell_result_1['peptide'].isin(["SYYPKHIQY","KLLCVHGVI"])]

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
3,1,SYYPKHIQY,66,74,9,HLA-A*02:01,66,4.6,SYYPKHIQY,SYYPKHIQY,0.011817,4.6
6,1,KLLCVHGVI,91,99,9,HLA-A*02:01,91,5.6,KLLCVHGVI,KLLCVHGVI,0.007818,5.6

In [145]:
t_cell_result_1.to_csv(path_or_buf="/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5/result_collection/2A_CTL/2A_CTL_with_score.csv")