### Here we will find out all the important epitope with different filtering

In [1]:
import pandas as pd
import numpy as np
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio import AlignIO
import os
import pathlib

In [2]:
os.chdir("/home/kaderi/Feroj/thesis/cross_validation")

In [395]:
alignment_vp1 = AlignIO.read("2C_aligned.fasta", "fasta")
print(alignment_vp1)

Alignment with 3 rows and 97 columns
LLIHGDPGCGKSLATTIVSRGLAAEGDIYSLPPNPKHFDGYNQQ...STN HRV-C36_2C
VLLHGNPGCGKSLATSVIARGLTTEAGVYSLPPDPKHFDGYDQQ...STN HRV-C41_2C
ILIHGGPGCGKSLATTIISRGLASEGDIYSLPPNPKHFDGYNQQ...STN HRV-C51_2C

In [429]:
epitope = "KSLCLLAWHNGKQQYE"
protein = alignment_vp1[2]

In [430]:
ep_len = len(epitope)
max_matches = 0
best_positions = []
best_sequences = []

# Slide the epitope along the protein to find the best match
for i in range(len(protein) - ep_len + 1):
    window = protein[i:i+ep_len]
    matches = sum(1 for a, b in zip(epitope, window) if a == b)
    
    if matches > max_matches:
        max_matches = matches
        best_positions = [i+1]  # +1 for 1-based position
        best_sequences = [window]
    elif matches == max_matches:
        best_positions.append(i+1)
        best_sequences.append(window)

percent_similarity = (max_matches / ep_len) * 100

print(f"Best similarity: {max_matches}/{ep_len} residues ({percent_similarity:.2f}%)")
print("Best matching region(s) in protein:")
for pos, seq in zip(best_positions, best_sequences):
    print(f"Position: {pos}, Sequence: {seq}")

Best similarity: 4/16 residues (25.00%)
Best matching region(s) in protein:
Position: 11, Sequence: ID: HRV-C51_2C
Name: HRV-C51_2C
Description: HRV-C51_2C RNA helicase; pfam00910
Number of features: 0
Seq('KSLATTIISRGLASEG')

In [ ]:
epitope = "YSLPPDPKY"
protein = alignment_vp1[0]

ep_len = len(epitope)
max_matches = 0

# Slide the epitope along the protein to find the best match##
for i in range(len(protein) - ep_len + 1):
    window = protein[i:i+ep_len]
    print(window)

ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('LLIHGDPGC')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('LIHGDPGCG')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('IHGDPGCGK')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('HGDPGCGKS')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GDPGCGKSL')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('DPGCGKSLA')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('PGCGKSLAT')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GCGKSLATT')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('CGKSLATTI')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GKSLATTIV')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('KSLATTIVS')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('SLATTIVSR')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('LATTIVSRG')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('ATTIVSRGL')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('TTIVSRGLA')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('TIVSRGLAA')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('IVSRGLAAE')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('VSRGLAAEG')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('SRGLAAEGD')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('RGLAAEGDI')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GLAAEGDIY')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('LAAEGDIYS')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('AAEGDIYSL')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('AEGDIYSLP')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('EGDIYSLPP')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GDIYSLPPN')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('DIYSLPPNP')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('IYSLPPNPK')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('YSLPPNPKH')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('SLPPNPKHF')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('LPPNPKHFD')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('PPNPKHFDG')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('PNPKHFDGY')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('NPKHFDGYN')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('PKHFDGYNQ')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('KHFDGYNQQ')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('HFDGYNQQK')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('FDGYNQQKV')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('DGYNQQKVV')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GYNQQKVVI')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('YNQQKVVIM')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('NQQKVVIMD')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('QQKVVIMDD')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('QKVVIMDDV')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('KVVIMDDVG')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('VVIMDDVGQ')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('VIMDDVGQN')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('IMDDVGQNP')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('MDDVGQNPD')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('DDVGQNPDG')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('DVGQNPDGE')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('VGQNPDGED')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GQNPDGEDL')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('QNPDGEDLG')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('NPDGEDLGI')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('PDGEDLGIF')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('DGEDLGIFC')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GEDLGIFCQ')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('EDLGIFCQM')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('DLGIFCQMV')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('LGIFCQMVS')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GIFCQMVST')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('IFCQMVSTT')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('FCQMVSTTD')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('CQMVSTTDF')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('QMVSTTDFH')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('MVSTTDFHV')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('VSTTDFHVP')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('STTDFHVPM')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('TTDFHVPMA')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('TDFHVPMAA')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('DFHVPMAAL')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('FHVPMAALE')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('HVPMAALED')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('VPMAALEDK')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('PMAALEDKG')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('MAALEDKGR')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('AALEDKGRC')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('ALEDKGRCF')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('LEDKGRCFT')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('EDKGRCFTS')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('DKGRCFTSD')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('KGRCFTSDY')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('GRCFTSDYV')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('RCFTSDYVL')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('CFTSDYVLA')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('FTSDYVLAS')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('TSDYVLAST')
ID: HRV-C36_2C
Name: HRV-C36_2C
Description: HRV-C36_2C RNA helicase; pfam00910
Number of features: 0
Seq('SDYVLASTN')

In [432]:

consensus_sequence = ""
for residue in range(0,alignment_vp1.get_alignment_length()):
    unique_chars = ""
    for i in alignment_vp1[:,residue]:
        if i in unique_chars:
            pass
        else:
            unique_chars+=i
    char_dict = dict()
    for j in unique_chars:

        char_dict.update({f"{j}":alignment_vp1[:,residue].count(j)})

    char_dict
    dict_value= list(char_dict.values())
    for keys, values in char_dict.items():
        
        if keys != "-":
        
            if values == max(dict_value):

                consensus_sequence+= keys
                break  ### if there is more than two residue occurs most then it will take the first one alphabetically
        else:
            dict_value.remove(max(dict_value))
            
            if values == max(dict_value):
                consensus_sequence+= keys
                break


consensus_sequence

'LLIHGDPGCGKSLATTIISRGLAAEGDIYSLPPNPKHFDGYNQQKVVIMDDVGQNPDGEDLGIFCQMVSTTDFHVPMAALEDKGKCFTSDYILASTN'

In [433]:
len(consensus_sequence)

97

In [434]:
# full_conserve_sequence =""
# for i in consensus_sequence:
#     if i != "-":
#         full_conserve_sequence += i
#     else:
#         pass
# full_conserve_sequence

In [435]:
conserved = ""
for i in range(alignment_vp1.get_alignment_length()):
    column = alignment_vp1[:, i]
    if column.count(column[0]) == len(column) and column[0] != "-":
        conserved += column[0]
    else:
        conserved += "-"

print("Conserved pattern:\n", conserved)

Conserved pattern:
 -L-HG-PGCGKSLAT----RGL--E---YSLPP-PKHFDGY-QQKVV-MDD-GQ-PDG-DL-IFCQMVSTTDF-VPMAA-E-KG--FTS-Y-LASTN

In [436]:
conserve_epitops= []
for i in conserved.split("-"):
    if len(i)>=5:
        conserve_epitops.append(i)
    else:
        pass
conserve_epitops

['PGCGKSLAT', 'YSLPP', 'PKHFDGY', 'QQKVV', 'IFCQMVSTTDF', 'VPMAA', 'LASTN']

In [437]:
"YSLPPD" in consensus_sequence

False

In [438]:
len(conserved)

97

In [439]:
## Here we will call the b cell/t-cell eptopes datafram

bpred_result = pd.read_csv(filepath_or_buffer="/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5/result_collection/t1_2A_iedb.csv")
bpred_result

FileNotFoundError: [Errno 2] No such file or directory: '/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5/result_collection/t1_2A_iedb.csv'

In [ ]:
#for t-cell 1
t_cell_result_1 = bpred_result[bpred_result["netmhcpan_el percentile"] <10]
t_cell_result_1

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
0,1,ILLALTADL,10,18,9,HLA-A*02:01,10,0.55,ILLALTADL,ILLALTADL,0.302525,0.55
1,1,ITAGGDNHV,102,110,9,HLA-A*02:01,102,2.90,ITAGGDNHV,ITAGGDNHV,0.029095,2.90
2,1,ILIGEGPCS,76,84,9,HLA-A*02:01,76,4.60,ILIGEGPCS,ILIGEGPCS,0.011978,4.60
3,1,SYYPKHIQY,66,74,9,HLA-A*02:01,66,4.60,SYYPKHIQY,SYYPKHIQY,0.011817,4.60
4,1,LALTADLQV,12,20,9,HLA-A*02:01,12,4.70,LALTADLQV,LALTADLQV,0.011289,4.70
5,1,CVAHDWYEI,54,62,9,HLA-A*02:01,54,5.20,CVAHDWYEI,CVAHDWYEI,0.009216,5.20
6,1,KLLCVHGVI,91,99,9,HLA-A*02:01,91,5.60,KLLCVHGVI,KLLCVHGVI,0.007818,5.60
7,1,NTILLALTA,8,16,9,HLA-A*02:01,8,6.10,NTILLALTA,NTILLALTA,0.006692,6.10
8,1,LTTPNDNTI,2,10,9,HLA-A*02:01,2,6.90,LTTPNDNTI,LTTPNDNTI,0.004973,6.90
9,1,TPNDNTILL,4,12,9,HLA-A*02:01,4,7.00,TPNDNTILL,TPNDNTILL,0.004950,7.00
10,1,IQYNILIGE,72,80,9,HLA-A*02:01,72,9.60,IQYNILIGE,IQYNILIGE,0.002339,9.60
11,1,DLQVDGANV,17,25,9,HLA-A*02:01,17,9.60,DLQVDGANV,DLQVDGANV,0.002327,9.60
12,1,KSRDRYYPV,44,52,9,HLA-A*02:01,44,9.80,KSRDRYYPV,KSRDRYYPV,0.002222,9.80

In [ ]:
# for bepripred
epitope_pred = ""

for i,j in enumerate(bpred_result["EpitopeProbability"]):
    if j < 0.5:
        epitope_pred+="-"
    else:
        epitope_pred+=bpred_result['AminoAcid'][i]
epitope_pred

'----SLNTIVA-GEWPSYLSDLDATSVDKPTHPETSSD-FYTLESVTWQGSSRGWWW--PDC-----VFGQNMYHHSMGRSGYIIHTQCNATKFHSGCL----VPEHQLAYIGGGGVNVKYEHTHPGEG-------GASNDRSNNNPDED-FFNCNGT-------FPHQMINLRTNNSSTIVV--------DNMLRHNNVSLV--------'

In [ ]:
## now we will cut the epitope separate then
epitope_to_check= []
for i in epitope_pred.split("-"):
    if len(i)>=7:
        epitope_to_check.append(i)
    else:
        pass
epitope_to_check

['SLNTIVA',
 'GEWPSYLSDLDATSVDKPTHPETSSD',
 'FYTLESVTWQGSSRGWWW',
 'VFGQNMYHHSMGRSGYIIHTQCNATKFHSGCL',
 'VPEHQLAYIGGGGVNVKYEHTHPGEG',
 'GASNDRSNNNPDED',
 'FFNCNGT',
 'FPHQMINLRTNNSSTIVV',
 'DNMLRHNNVSLV']

In [ ]:
##for t-cell
## now we will cut the epitope separate then

epitope_to_check = t_cell_result_1['peptide'].values
epitope_to_check

array(['ILLALTADL', 'ITAGGDNHV', 'ILIGEGPCS', 'SYYPKHIQY', 'LALTADLQV',
       'CVAHDWYEI', 'KLLCVHGVI', 'NTILLALTA', 'LTTPNDNTI', 'TPNDNTILL',
       'IQYNILIGE', 'DLQVDGANV', 'KSRDRYYPV'], dtype=object)

In [ ]:
conserve_epitops= []
for i in conserved.split("-"):
    if len(i)>=5:
        conserve_epitops.append(i)
    else:
        pass
conserve_epitops

['YYPKHIQY', 'PGDCGGKLLC']

In [ ]:

result_table = pd.DataFrame(columns=("conserve_regions",
                                     'candidate_epitope',
                                     'conservence_presence'))
for a in conserve_epitops:
    l = ''
    k = ''
    for i in range(0,len(a)):

        b = a[i:]
        if b in l:
            break
        elif len(b)>=4:
            for epitopes in epitope_to_check:
                if b in epitopes:
                    print(f"{b} present in {epitopes}")
                    l += b
                    result_table_1 = pd.DataFrame({
                                        "conserve_regions":[a],
                                        "candidate_epitope":[epitopes],
                                        "conservence_presence":[l]})
                    result_table = pd.concat((result_table,result_table_1),axis = 0)
                    break

YYPKHIQY present in SYYPKHIQY
KLLC present in KLLCVHGVI

In [ ]:
result_table.describe()

       conserve_regions candidate_epitope conservence_presence
count                 2                 2                    2
unique                2                 2                    2
top            YYPKHIQY         SYYPKHIQY             YYPKHIQY
freq                  1                 1                    1

In [ ]:
result_table["candidate_epitope"].unique()

array(['SYYPKHIQY', 'KLLCVHGVI'], dtype=object)

In [ ]:
conserve_regions_table = []
candidate_epitope_table = []
conserve_epitope_presence = []
for i in result_table["candidate_epitope"].unique():
    index_conserve = result_table[result_table["candidate_epitope"]== i ]['conserve_regions'].values
    presence_conserve = result_table[result_table["candidate_epitope"]== i ]['conservence_presence'].values
    conserve_epitope_region_table = ''
    conserve_epitope_presence_table = ''
    if len(index_conserve)> 1:
        for j in index_conserve:
            conserve_epitope_region_table += f"{j}"
            conserve_epitope_region_table += ","
        for k in presence_conserve:
            conserve_epitope_presence_table += f"{k}"
            conserve_epitope_presence_table += ","
    else:
        conserve_epitope_region_table += f"{index_conserve[0]}"
        conserve_epitope_presence_table += f"{presence_conserve[0]}"
    conserve_regions_table.append(i)
    candidate_epitope_table.append(conserve_epitope_region_table)
    conserve_epitope_presence.append(conserve_epitope_presence_table)

In [ ]:
final_table = pd.DataFrame({"conserve_region":candidate_epitope_table,
                            "epitope":conserve_regions_table,
                            "conservence_presence":conserve_epitope_presence,
                            })
final_table

  conserve_region    epitope conservence_presence
0        YYPKHIQY  SYYPKHIQY             YYPKHIQY
1      PGDCGGKLLC  KLLCVHGVI                 KLLC

In [ ]:
final_table.to_csv(path_or_buf="/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5/result_collection/2A_CTL/2A_CTL_final_candidate_epitope.csv")

In [ ]:
t_cell_result_1[t_cell_result_1['peptide'].isin(["SYYPKHIQY","KLLCVHGVI"])]

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhcpan_el core,netmhcpan_el icore,netmhcpan_el score,netmhcpan_el percentile
3,1,SYYPKHIQY,66,74,9,HLA-A*02:01,66,4.6,SYYPKHIQY,SYYPKHIQY,0.011817,4.6
6,1,KLLCVHGVI,91,99,9,HLA-A*02:01,91,5.6,KLLCVHGVI,KLLCVHGVI,0.007818,5.6

In [ ]:
t_cell_result_1.to_csv(path_or_buf="/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5/result_collection/2A_CTL/2A_CTL_with_score.csv")