### Here we will find out all the important epitope with different filtering

In [18]:
import pandas as pd
import numpy as np
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio import AlignIO
import os
import pathlib

In [20]:
os.chdir("/home/kaderi/Feroj/thesis/HRV-C/Data_collecton/hrv-top5")

In [130]:
alignment_vp1 = AlignIO.read("vp4_aligned.fasta", "fasta")
print(alignment_vp1)
print(alignment_vp1.get_alignment_length())

Alignment with 5 rows and 66 columns
GAQVSKQNVGSHENSVSASGGSVIKYFNINYYKDSASSGLTKQD...ALM HRV-C2_VP4
GAQVSRQSVGSHETMIHAGTGAVVKYFNVNYYKDAASSGLTKQD...ALM HRV-C6_VP4
GAQVSRQKVGSHDNAINASSGSVVKYFNINYYKDAASSGLSKQD...ALM HRV-C9_VP4
GAQVSRQNNGTHESGVTANNGSVIKYFNINYYKDSASSGLSRQD...ALM HRV-C15_VP4
GAQVSKQSVGAHETTVHAGSGAVVKYFNINYYKDAASSGLTKQD...ALM HRV-C43_VP4
66

In [131]:

consensus_sequence = ""
for residue in range(0,alignment_vp1.get_alignment_length()):
    unique_chars = ""
    for i in alignment_vp1[:,residue]:
        if i in unique_chars:
            pass
        else:
            unique_chars+=i
    char_dict = dict()

    for j in unique_chars:

        char_dict.update({f"{j}":alignment_vp1[:,residue].count(j)})


    keys = char_dict.keys()
    if '-' in keys:
        char_dict.pop("-")

    dict_value= list(char_dict.values())

    for keys, values in char_dict.items():
        if values == max(dict_value):
            consensus_sequence += keys
            break

                    

print(consensus_sequence)
print(len(consensus_sequence))

GAQVSRQNVGSHENSVHASSGSVVKYFNINYYKDAASSGLTKQDFSQDPSKFTQPVADVLTNPALM
66

In [132]:
conserved = ""
for i in range(alignment_vp1.get_alignment_length()):
    column = alignment_vp1[:, i]
    if column.count(column[0]) == len(column) and column[0] != "-":
        conserved += column[0]
    else:
        conserved += "-"

print("Conserved pattern:\n", conserved)
print(len(conserved))

Conserved pattern:
 GAQVS-Q--G-H-----A--G-V-KYFN-NYYKD-ASSGL--QDFSQDPSKFTQP----L-NPALM
66

In [133]:
## Here we will call the t-cell eptopes dataframe

tcel1_result = pd.read_csv(filepath_or_buffer="result_collection/VP4_HTL/VP4_HTL_ALL_ALLEL.csv")
tcel1_result

,seq #,peptide,start,end,peptide length,allele,peptide index,median binding percentile,netmhciipan_el core,netmhciipan_el score,netmhciipan_el percentile
0,1,YFNINYYKDAASSGL,26,40,15,HLA-DQA1*01:01/DQB1*05:01,6,0.04,INYYKDAAS,0.104108,0.04
1,1,YFNINYYKDAASSGL,26,40,15,HLA-DRB1*15:01,6,0.14,INYYKDAAS,0.896855,0.14
2,1,GSVVKYFNINYYKDA,21,35,15,HLA-DRB1*12:01,5,0.36,VKYFNINYY,0.729358,0.36
3,1,GSVVKYFNINYYKDA,21,35,15,HLA-DQA1*01:01/DQB1*05:01,5,0.58,VKYFNINYY,0.040162,0.58
4,1,TKQDFSQDPSKFTQP,41,55,15,HLA-DRB3*01:01,9,0.62,FSQDPSKFT,0.621991,0.62
...,...,...,...,...,...,...,...,...,...,...,...
292,1,VHASSGSVVKYFNIN,16,30,15,HLA-DRB1*03:01,4,95.00,SSGSVVKYF,0.000314,95.00
293,1,VHASSGSVVKYFNIN,16,30,15,HLA-DRB4*01:01,4,96.00,GSVVKYFNI,0.000818,96.00
294,1,VHASSGSVVKYFNIN,16,30,15,HLA-DRB1*04:05,4,96.00,SSGSVVKYF,0.000466,96.00
295,1,VHASSGSVVKYFNIN,16,30,15,HLA-DRB5*01:01,4,96.00,SGSVVKYFN,0.000445,96.00
296,1,VHASSGSVVKYFNIN,16,30,15,HLA-DRB1*04:01,4,98.00,SSGSVVKYF,0.000200,98.00

In [134]:

# Now we use second filtering if it's available, we will keep those peptide which percentile is less than 10
# we will write the programm if all the value less than one it will keep the data frame as it is, otherwise if will filter out
tcel1_result_filter_1 = tcel1_result[tcel1_result["netmhciipan_el percentile"] < 10]

### we will move to third filter where we will remove the duplicates

# tcel1_result_filter_3 = tcel1_result_filter_2.drop_duplicates(subset="peptide",ignore_index= True)
# tcel1_result_filter_3

In [135]:


peptide = []
new_allel= []
for i in tcel1_result_filter_1["peptide"].unique():
    allel_for_similar_epitope = tcel1_result_filter_1[tcel1_result_filter_1["peptide"]== i ]['allele'].values
    allels = ''
    if len(allel_for_similar_epitope)> 1:
        for j in allel_for_similar_epitope:
            allels += f"{j}"
            allels += ","
    else:
        allels += f"{allel_for_similar_epitope[0]}"
    peptide.append(i)
    new_allel.append(allels) 

print(new_allel)

['HLA-DQA1*01:01/DQB1*05:01,HLA-DRB1*15:01,HLA-DQA1*04:01/DQB1*04:02,HLA-DRB1*04:01,HLA-DRB3*01:01,HLA-DRB3*02:02,HLA-DRB1*04:05,HLA-DQA1*03:01/DQB1*03:02,', 'HLA-DRB1*12:01,HLA-DQA1*01:01/DQB1*05:01,HLA-DRB1*15:01,HLA-DQA1*04:01/DQB1*04:02,HLA-DPA1*02:01/DPB1*05:01,HLA-DPA1*02:01/DPB1*01:01,HLA-DPA1*01:03/DPB1*04:01,HLA-DPA1*01:03/DPB1*02:01,HLA-DQA1*03:01/DQB1*03:02,HLA-DPA1*03:01/DPB1*04:02,HLA-DRB1*13:02,HLA-DRB4*01:01,', 'HLA-DRB3*01:01,HLA-DRB1*04:01,HLA-DRB3*02:02,', 'HLA-DRB1*09:01,HLA-DRB1*07:01,HLA-DQA1*05:01/DQB1*03:01,', 'HLA-DRB4*01:01,HLA-DPA1*02:01/DPB1*14:01,', 'HLA-DPA1*01:03/DPB1*04:01,HLA-DPA1*02:01/DPB1*01:01,', 'HLA-DRB1*04:01,HLA-DRB1*04:05,', 'HLA-DQA1*01:02/DQB1*06:02', 'HLA-DQA1*01:02/DQB1*06:02']

In [136]:
tcel1_result_filter_3 = pd.DataFrame({'peptide':peptide,'allel':new_allel})
print(tcel1_result_filter_3.shape)

(9, 2)

#### Now we will match those peptides with conserve regions

In [137]:
# # for bepripred
# epitope_pred = ""

# for i,j in enumerate(bpred_result["EpitopeProbability"]):
#     if j < 0.5:
#         epitope_pred+="-"
#     else:
#         epitope_pred+=bpred_result['AminoAcid'][i]
# epitope_pred

In [138]:
# ## now we will cut the epitope separate then
# epitope_to_check= []
# for i in epitope_pred.split("-"):
#     if len(i)>=7:
#         epitope_to_check.append(i)
#     else:
#         pass
# epitope_to_check

In [139]:
epitope_to_check = tcel1_result_filter_3['peptide'].values
epitope_to_check

array(['YFNINYYKDAASSGL', 'GSVVKYFNINYYKDA', 'TKQDFSQDPSKFTQP',
       'SHENSVHASSGSVVK', 'GAQVSRQNVGSHENS', 'ASSGLTKQDFSQDPS',
       'KFTQPVADVLTNPAL', 'VHASSGSVVKYFNIN', 'RQNVGSHENSVHASS'],
      dtype=object)

In [140]:
conserve_epitops= []
for i in conserved.split("-"):
    if len(i)>=5:
        conserve_epitops.append(i)
    else:
        pass
conserve_epitops

['GAQVS', 'NYYKD', 'ASSGL', 'QDFSQDPSKFTQP', 'NPALM']

In [141]:

result_table = pd.DataFrame(columns=("conserve_regions",
                                     'candidate_epitope',
                                     'conservence_presence'))
for a in conserve_epitops:
    l = ''
    k = ''
    for i in range(0,len(a)):

        b = a[i:]
        if b in l:
            break
        elif len(b)>=4:
            for epitopes in epitope_to_check:
                if b in epitopes:
                    print(f"{b} present in {epitopes}")
                    l += b
                    result_table_1 = pd.DataFrame({
                                        "conserve_regions":[a],
                                        "candidate_epitope":[epitopes],
                                        "conservence_presence":[l]})
                    result_table = pd.concat((result_table,result_table_1),axis = 0)
                    break
                
result_table.describe()

GAQVS present in GAQVSRQNVGSHENS
NYYKD present in YFNINYYKDAASSGL
ASSGL present in YFNINYYKDAASSGL
QDFSQDPSKFTQP present in TKQDFSQDPSKFTQP

       conserve_regions candidate_epitope conservence_presence
count                 4                 4                    4
unique                4                 3                    4
top               GAQVS   YFNINYYKDAASSGL                GAQVS
freq                  1                 2                    1

In [142]:
allel_finder = result_table["candidate_epitope"].values.tolist()
allel_finder
allels_to_add = list()
for j in allel_finder:
    var_1 = tcel1_result_filter_3[tcel1_result_filter_3['peptide'] == j]
    allels_to_add.append(var_1['allel'].values[0])

    

result_table['allel'] = allels_to_add

In [143]:
conserve_regions_table = []
candidate_epitope_table = []
conserve_epitope_presence = []
allel_table = []
for i in result_table["conserve_regions"].unique():
    candidate_epitope_conserve = result_table[result_table["conserve_regions"]== i ]['candidate_epitope'].values
    presence_conserve = result_table[result_table["conserve_regions"]== i ]['conservence_presence'].values
    allels_unique = result_table[result_table["conserve_regions"]== i ]['allel'].values
    candidate_epitope_region_table = ''
    conserve_epitope_presence_table = ''
    allel_presence_table = ''
    if len(candidate_epitope_conserve)> 1:
        for j in candidate_epitope_conserve:
            candidate_epitope_region_table += f"{j}"
            candidate_epitope_region_table += ","
        for k in presence_conserve:
            conserve_epitope_presence_table += f"{k}"
            conserve_epitope_presence_table += ","
        for l in allels_unique:
            allel_presence_table += f"{l}"
            allel_presence_table += ","
    else:
        candidate_epitope_region_table += f"{candidate_epitope_conserve[0]}"
        conserve_epitope_presence_table += f"{presence_conserve[0]}"
        allel_presence_table += f"{allels_unique[0]}"

    conserve_regions_table.append(candidate_epitope_region_table)
    candidate_epitope_table.append(i)
    conserve_epitope_presence.append(conserve_epitope_presence_table)   
    allel_table.append(allel_presence_table)

final_table = pd.DataFrame({"conserve_region":candidate_epitope_table,
                            "epitope":conserve_regions_table,
                            "conservence_presence":conserve_epitope_presence,
                            "allel":allel_table
                            })
final_table

,conserve_region,epitope,conservence_presence,allel
0,GAQVS,GAQVSRQNVGSHENS,GAQVS,"HLA-DRB4*01:01,HLA-DPA1*02:01/DPB1*14:01,"
1,NYYKD,YFNINYYKDAASSGL,NYYKD,"HLA-DQA1*01:01/DQB1*05:01,HLA-DRB1*15:01,HLA-D..."
2,ASSGL,YFNINYYKDAASSGL,ASSGL,"HLA-DQA1*01:01/DQB1*05:01,HLA-DRB1*15:01,HLA-D..."
3,QDFSQDPSKFTQP,TKQDFSQDPSKFTQP,QDFSQDPSKFTQP,"HLA-DRB3*01:01,HLA-DRB1*04:01,HLA-DRB3*02:02,"

In [144]:
final_table.to_csv(path_or_buf="result_collection/new results/VP4_HTL_final_candidate_epitope_with_allel.csv")

In [145]:
# filtered_final = tcel1_result[tcel1_result['peptide'].isin(final_table["epitope"].values)]
# filtered_final